### PR TITLE
use git submodule for library sources

### PR DESCRIPTION
**Pull request by remicollet**
To simply bundled library management, as explained in #7

### CODE REVIEW

**Comment by remicollet** [comment]
@cmb69 your help welcome for needed change in `config.w32` for this one (and perhaps CI)


P.S. CI is now green for linux

**Comment by cmb69** [comment]
We're hitting https://github.com/php/php-src/issues/16843 now (md4c.c and libmd4c/src/md4c.c). To avoid that (fix is unlikely to land for stable PHP versions), might be best to rename md4c.c to php_md4c.c or something. Then a minimal solution for Windows would be:

````diff
 config.w32           | 9 ++++++++-
 md4c.c => php_md4c.c | 0
 2 files changed, 8 insertions(+), 1 deletion(-)

diff --git a/config.w32 b/config.w32
index 01b0921..851f590 100644
--- a/config.w32
+++ b/config.w32
@@ -1,5 +1,12 @@
 ARG_ENABLE('md4c', 'Enable the md4c extension', 'no');
 
 if (PHP_MD4C != 'no') {
-    EXTENSION('md4c', 'md4c.c');
+    EXTENSION('md4c', 'php_md4c.c');
+    ADD_SOURCES(configure_module_dirname + "/libmd4c/src", "\
+        entity.c \
+        md4c.c \
+        md4c-html.c",
+        "md4c"
+    );
+    CHECK_HEADER_ADD_INCLUDE("md4c-html.h", "CFLAGS_MD4C", "libmd4c/src/");
 }
diff --git a/md4c.c b/php_md4c.c
similarity index 100%
rename from md4c.c
rename to php_md4c.c
````
That should also be sufficient for CI.

That could also be extended to support `--enable-system-libmd4c` on Windows, although that would require https://github.com/winlibs to actually build this library, and given it is at 0.52, and not used so far by other packages, might not make much sense.

Also I wonder why there is an explicit `--enable-system-libmd4c` at all; could just run pkg-config, and if system lib is found use that; otherwise fall back to bundled.

**Comment by remicollet** [comment]
@cmb69 thanks, applied

> Also I wonder why there is an explicit --enable-system-libmd4c at all

Some user may prefer the bundled lib instead of system one, ex: when too old

I already think about a 3 states option (yes/no/auto), but IIRC from another ext, this was not a success, probably need to try again

@eklausme this PR is now broken because you create the submodule. Feel free to pick  what is needed here which have everything needed for linux, windows and CI

**Comment by remicollet** [comment]
Rebased, and CI is green on  Windows and Linux (with bundled or system library)

**Comment by remicollet** [comment]
@cmb69 see last commit which add "auto" mode

* without option, use system library if available
* `--enable-system-libmd4c` always use system library, fails if not available
* -`-disable-system-libmd4c` always use bundled library, ignore system

**Comment by cmb69** [comment]
Thanks @remicollet, I think the option changes make sense.

**Pull request merged**
